# Generated by Django 5.0.6 on 2024-06-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaInfo',
            fields=[
                ('uuid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('hash_value', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
