# Generated by Django 5.0.6 on 2024-06-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediainfo',
            name='uuid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
