# Generated by Django 5.0.6 on 2024-09-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediainfo',
            name='user',
        ),
    ]
