# Generated by Django 5.0.6 on 2024-09-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mediainfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediainfo',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
